"""Added account table

Revision ID: 266b1223bfc7
Revises: 
Create Date: 2023-04-26 08:02:57.210138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266b1223bfc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Question model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth user model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth user model')
    op.drop_table('Question model')
    # ### end Alembic commands ###
